# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: w:/vivado/cvtcolor-gray-8/cvtcolor-gray-8.srcs/sources_1/bd/design_1/ip/design_1_cvtcolor_og_0_0/design_1_cvtcolor_og_0_0.xci
# IP: The module: 'design_1_cvtcolor_og_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/vivado/cvtcolor-gray-8/cvtcolor-gray-8.gen/sources_1/bd/design_1/ip/design_1_cvtcolor_og_0_0/constraints/cvtcolor_og_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cvtcolor_og_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: w:/vivado/cvtcolor-gray-8/cvtcolor-gray-8.srcs/sources_1/bd/design_1/ip/design_1_cvtcolor_og_0_0/design_1_cvtcolor_og_0_0.xci
# IP: The module: 'design_1_cvtcolor_og_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/vivado/cvtcolor-gray-8/cvtcolor-gray-8.gen/sources_1/bd/design_1/ip/design_1_cvtcolor_og_0_0/constraints/cvtcolor_og_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_cvtcolor_og_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
