<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop</name>
		<module_structure>Sequential</module_structure>
		<ret_bitwidth>0</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>3</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1702129263</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>imgInput0_data</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1702129263</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>24</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_3">
				<Value>
					<Obj>
						<type>1</type>
						<id>3</id>
						<name>imgOutput0_data</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1702129263</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<direction>1</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>27</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_4">
				<Value>
					<Obj>
						<type>0</type>
						<id>4</id>
						<name>j</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1480209080</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>41</item>
				</oprand_edges>
				<opcode>alloca</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>1</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_5">
				<Value>
					<Obj>
						<type>0</type>
						<id>7</id>
						<name>tmp</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>5623</lineNumber>
						<contextFuncName>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</contextFuncName>
						<contextNormFuncName>bgr2gray_16_0_1080_1920_1_2_2_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>1</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5623</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>979857001</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>43</item>
					<item>44</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>2</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>8</id>
						<name>j_write_ln0</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1463551460</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>46</item>
					<item>47</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.58</m_delay>
				<m_topoIndex>3</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_7">
				<Value>
					<Obj>
						<type>0</type>
						<id>9</id>
						<name>br_ln0</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>0</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>48</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>4</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_8">
				<Value>
					<Obj>
						<type>0</type>
						<id>11</id>
						<name>j_load</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>5582</lineNumber>
						<contextFuncName>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</contextFuncName>
						<contextNormFuncName>xfbgr2gray_16_0_1080_1920_1_2_2_10_1_1036800_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5582</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>49</item>
					<item>170</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>5</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>12</id>
						<name>icmp_ln5582</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>5582</lineNumber>
						<contextFuncName>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</contextFuncName>
						<contextNormFuncName>xfbgr2gray_16_0_1080_1920_1_2_2_10_1_1036800_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5582</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4294967295</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>50</item>
					<item>51</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>2.07</m_delay>
				<m_topoIndex>6</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>13</id>
						<name>add_ln5582</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>5582</lineNumber>
						<contextFuncName>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</contextFuncName>
						<contextNormFuncName>xfbgr2gray_16_0_1080_1920_1_2_2_10_1_1036800_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5582</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>66</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>52</item>
					<item>54</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>2.07</m_delay>
				<m_topoIndex>7</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>14</id>
						<name>br_ln5582</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>5582</lineNumber>
						<contextFuncName>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</contextFuncName>
						<contextNormFuncName>xfbgr2gray_16_0_1080_1920_1_2_2_10_1_1036800_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5582</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>539766833</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>55</item>
					<item>56</item>
					<item>57</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>8</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>19</id>
						<name>pix</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\common/xf_structs.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>542</lineNumber>
						<contextFuncName>read&amp;lt;2, nullptr&amp;gt;</contextFuncName>
						<contextNormFuncName>read_2_nullptr_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\common/xf_structs.hpp</first>
											<second>read&amp;lt;2, nullptr&amp;gt;</second>
										</first>
										<second>542</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5588</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>pix</originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1718558821</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>24</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>59</item>
					<item>60</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>3.63</m_delay>
				<m_topoIndex>10</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>20</id>
						<name>p</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>155</lineNumber>
						<contextFuncName>ExtractUYVYPixels&amp;lt;10&amp;gt;</contextFuncName>
						<contextNormFuncName>ExtractUYVYPixels_10_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5589</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>ExtractUYVYPixels&amp;lt;10&amp;gt;</second>
										</first>
										<second>155</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>p</originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4228300630</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>61</item>
				</oprand_edges>
				<opcode>trunc</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>11</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>21</id>
						<name>p_1</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>155</lineNumber>
						<contextFuncName>ExtractUYVYPixels&amp;lt;10&amp;gt;</contextFuncName>
						<contextNormFuncName>ExtractUYVYPixels_10_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5589</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>ExtractUYVYPixels&amp;lt;10&amp;gt;</second>
										</first>
										<second>155</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>p</originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1296906810</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>63</item>
					<item>64</item>
					<item>66</item>
					<item>68</item>
				</oprand_edges>
				<opcode>partselect</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>12</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>22</id>
						<name>p_2</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>155</lineNumber>
						<contextFuncName>ExtractUYVYPixels&amp;lt;10&amp;gt;</contextFuncName>
						<contextNormFuncName>ExtractUYVYPixels_10_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5589</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>ExtractUYVYPixels&amp;lt;10&amp;gt;</second>
										</first>
										<second>155</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>p</originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1629888521</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>69</item>
					<item>70</item>
					<item>72</item>
					<item>74</item>
				</oprand_edges>
				<opcode>partselect</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>13</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>23</id>
						<name>zext_ln886</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>4228300630</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>22</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>75</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>16</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>24</id>
						<name>zext_ln886_1</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>0</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>23</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>76</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>17</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>25</id>
						<name>zext_ln886_2</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>6563104</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>20</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>77</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>14</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>26</id>
						<name>mul_ln886</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>674985063</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>22</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>78</item>
					<item>80</item>
				</oprand_edges>
				<opcode>mul</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>5.59</m_delay>
				<m_topoIndex>18</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>27</id>
						<name>mul_ln886_1</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>0</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>23</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>81</item>
					<item>83</item>
				</oprand_edges>
				<opcode>mul</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.05</m_delay>
				<m_topoIndex>19</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>28</id>
						<name>mul_ln886_2</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1885415011</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>20</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>84</item>
					<item>86</item>
				</oprand_edges>
				<opcode>mul</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.05</m_delay>
				<m_topoIndex>15</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_22">
				<Value>
					<Obj>
						<type>0</type>
						<id>29</id>
						<name>zext_ln886_3</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>544108393</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>22</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>87</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>20</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_23">
				<Value>
					<Obj>
						<type>0</type>
						<id>30</id>
						<name>add_ln886</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>976905848</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>22</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>88</item>
					<item>89</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>2.10</m_delay>
				<m_topoIndex>21</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_24">
				<Value>
					<Obj>
						<type>0</type>
						<id>31</id>
						<name>zext_ln886_4</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>55</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>23</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>90</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>22</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_25">
				<Value>
					<Obj>
						<type>0</type>
						<id>32</id>
						<name>GRAY</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>886</lineNumber>
						<contextFuncName>CalculateGRAY</contextFuncName>
						<contextNormFuncName>CalculateGRAY</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>886</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>GRAY</originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>0</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>23</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>91</item>
					<item>92</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>2.10</m_delay>
				<m_topoIndex>23</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_26">
				<Value>
					<Obj>
						<type>0</type>
						<id>33</id>
						<name>Value_uchar</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>766</lineNumber>
						<contextFuncName>saturate_cast</contextFuncName>
						<contextNormFuncName>saturate_cast</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>4</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5594</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>CalculateGRAY</second>
										</first>
										<second>887</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color_utils.hpp</first>
											<second>saturate_cast</second>
										</first>
										<second>766</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>Value_uchar</originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>840969265</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>94</item>
					<item>95</item>
					<item>96</item>
					<item>98</item>
				</oprand_edges>
				<opcode>partselect</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>25</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_27">
				<Value>
					<Obj>
						<type>0</type>
						<id>34</id>
						<name>imgOutput0_data_write_ln553</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\common/xf_structs.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>553</lineNumber>
						<contextFuncName>write&amp;lt;2, nullptr&amp;gt;</contextFuncName>
						<contextNormFuncName>write_2_nullptr_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\common/xf_structs.hpp</first>
											<second>write&amp;lt;2, nullptr&amp;gt;</second>
										</first>
										<second>553</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5598</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>997485606</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>100</item>
					<item>101</item>
					<item>102</item>
				</oprand_edges>
				<opcode>write</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>3.63</m_delay>
				<m_topoIndex>26</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_28">
				<Value>
					<Obj>
						<type>0</type>
						<id>35</id>
						<name>j_write_ln5582</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>5582</lineNumber>
						<contextFuncName>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</contextFuncName>
						<contextNormFuncName>xfbgr2gray_16_0_1080_1920_1_2_2_10_1_1036800_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5582</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>825372721</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>103</item>
					<item>104</item>
					<item>171</item>
					<item>172</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.58</m_delay>
				<m_topoIndex>9</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_29">
				<Value>
					<Obj>
						<type>0</type>
						<id>36</id>
						<name>br_ln5582</name>
						<fileName>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</fileName>
						<fileDirectory>W:\vitis_workspace\ip24\att4\hls_component</fileDirectory>
						<lineNumber>5582</lineNumber>
						<contextFuncName>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</contextFuncName>
						<contextNormFuncName>xfbgr2gray_16_0_1080_1920_1_2_2_10_1_1036800_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>W:\vitis_workspace\ip24\att4\hls_component</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>bgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2&amp;gt;</second>
										</first>
										<second>5622</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vitis_Libraries/vision/L1/include\imgproc/xf_cvt_color.hpp</first>
											<second>xfbgr2gray&amp;lt;16, 0, 1080, 1920, 1, 2, 2, 10, 1, 1036800&amp;gt;</second>
										</first>
										<second>5582</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1885413420</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>105</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>27</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_30">
				<Value>
					<Obj>
						<type>0</type>
						<id>38</id>
						<name>_ln0</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1768713801</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>0</count>
					<item_version>0</item_version>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>24</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>11</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_31">
				<Value>
					<Obj>
						<type>2</type>
						<id>40</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1931485194</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_32">
				<Value>
					<Obj>
						<type>2</type>
						<id>45</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1717897790</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_33">
				<Value>
					<Obj>
						<type>2</type>
						<id>53</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1702129263</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_34">
				<Value>
					<Obj>
						<type>2</type>
						<id>65</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1702129263</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>8</content>
			</item>
			<item class_id_reference="16" object_id="_35">
				<Value>
					<Obj>
						<type>2</type>
						<id>67</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1702129263</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>15</content>
			</item>
			<item class_id_reference="16" object_id="_36">
				<Value>
					<Obj>
						<type>2</type>
						<id>71</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>779318371</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>16</content>
			</item>
			<item class_id_reference="16" object_id="_37">
				<Value>
					<Obj>
						<type>2</type>
						<id>73</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1296906810</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>23</content>
			</item>
			<item class_id_reference="16" object_id="_38">
				<Value>
					<Obj>
						<type>2</type>
						<id>79</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1702125925</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>22</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>9798</content>
			</item>
			<item class_id_reference="16" object_id="_39">
				<Value>
					<Obj>
						<type>2</type>
						<id>82</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1310735648</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>23</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>19235</content>
			</item>
			<item class_id_reference="16" object_id="_40">
				<Value>
					<Obj>
						<type>2</type>
						<id>85</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>741482540</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>20</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>3736</content>
			</item>
			<item class_id_reference="16" object_id="_41">
				<Value>
					<Obj>
						<type>2</type>
						<id>97</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1818455657</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>22</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>4</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_42">
				<Obj>
					<type>3</type>
					<id>10</id>
					<name>newFuncRoot</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>0</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>4</item>
					<item>7</item>
					<item>8</item>
					<item>9</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_43">
				<Obj>
					<type>3</type>
					<id>15</id>
					<name>VITIS_LOOP_5590_1.i</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>0</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>11</item>
					<item>12</item>
					<item>13</item>
					<item>14</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_44">
				<Obj>
					<type>3</type>
					<id>37</id>
					<name>VITIS_LOOP_5590_1.i.split</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>1953066581</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>18</count>
					<item_version>0</item_version>
					<item>19</item>
					<item>20</item>
					<item>21</item>
					<item>22</item>
					<item>23</item>
					<item>24</item>
					<item>25</item>
					<item>26</item>
					<item>27</item>
					<item>28</item>
					<item>29</item>
					<item>30</item>
					<item>31</item>
					<item>32</item>
					<item>33</item>
					<item>34</item>
					<item>35</item>
					<item>36</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_45">
				<Obj>
					<type>3</type>
					<id>39</id>
					<name>for.inc51.i.loopexit.exitStub</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>0</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>38</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>51</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_46">
				<id>41</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>4</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_47">
				<id>44</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>7</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_48">
				<id>46</id>
				<edge_type>1</edge_type>
				<source_obj>45</source_obj>
				<sink_obj>8</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_49">
				<id>47</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>8</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_50">
				<id>48</id>
				<edge_type>2</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>9</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_51">
				<id>49</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>11</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_52">
				<id>50</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>12</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_53">
				<id>51</id>
				<edge_type>1</edge_type>
				<source_obj>7</source_obj>
				<sink_obj>12</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_54">
				<id>52</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>13</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_55">
				<id>54</id>
				<edge_type>1</edge_type>
				<source_obj>53</source_obj>
				<sink_obj>13</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_56">
				<id>55</id>
				<edge_type>1</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>14</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_57">
				<id>56</id>
				<edge_type>2</edge_type>
				<source_obj>37</source_obj>
				<sink_obj>14</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_58">
				<id>57</id>
				<edge_type>2</edge_type>
				<source_obj>39</source_obj>
				<sink_obj>14</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_59">
				<id>60</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>19</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_60">
				<id>61</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>20</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_61">
				<id>64</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>21</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_62">
				<id>66</id>
				<edge_type>1</edge_type>
				<source_obj>65</source_obj>
				<sink_obj>21</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_63">
				<id>68</id>
				<edge_type>1</edge_type>
				<source_obj>67</source_obj>
				<sink_obj>21</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_64">
				<id>70</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>22</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_65">
				<id>72</id>
				<edge_type>1</edge_type>
				<source_obj>71</source_obj>
				<sink_obj>22</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>74</id>
				<edge_type>1</edge_type>
				<source_obj>73</source_obj>
				<sink_obj>22</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>75</id>
				<edge_type>1</edge_type>
				<source_obj>22</source_obj>
				<sink_obj>23</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_68">
				<id>76</id>
				<edge_type>1</edge_type>
				<source_obj>21</source_obj>
				<sink_obj>24</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_69">
				<id>77</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>25</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_70">
				<id>78</id>
				<edge_type>1</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>26</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_71">
				<id>80</id>
				<edge_type>1</edge_type>
				<source_obj>79</source_obj>
				<sink_obj>26</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_72">
				<id>81</id>
				<edge_type>1</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>27</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_73">
				<id>83</id>
				<edge_type>1</edge_type>
				<source_obj>82</source_obj>
				<sink_obj>27</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_74">
				<id>84</id>
				<edge_type>1</edge_type>
				<source_obj>25</source_obj>
				<sink_obj>28</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_75">
				<id>86</id>
				<edge_type>1</edge_type>
				<source_obj>85</source_obj>
				<sink_obj>28</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_76">
				<id>87</id>
				<edge_type>1</edge_type>
				<source_obj>28</source_obj>
				<sink_obj>29</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_77">
				<id>88</id>
				<edge_type>1</edge_type>
				<source_obj>26</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_78">
				<id>89</id>
				<edge_type>1</edge_type>
				<source_obj>29</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_79">
				<id>90</id>
				<edge_type>1</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>31</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_80">
				<id>91</id>
				<edge_type>1</edge_type>
				<source_obj>31</source_obj>
				<sink_obj>32</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_81">
				<id>92</id>
				<edge_type>1</edge_type>
				<source_obj>27</source_obj>
				<sink_obj>32</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_82">
				<id>95</id>
				<edge_type>1</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>33</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_83">
				<id>96</id>
				<edge_type>1</edge_type>
				<source_obj>67</source_obj>
				<sink_obj>33</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_84">
				<id>98</id>
				<edge_type>1</edge_type>
				<source_obj>97</source_obj>
				<sink_obj>33</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_85">
				<id>101</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>34</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_86">
				<id>102</id>
				<edge_type>1</edge_type>
				<source_obj>33</source_obj>
				<sink_obj>34</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_87">
				<id>103</id>
				<edge_type>1</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>35</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_88">
				<id>104</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>35</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_89">
				<id>105</id>
				<edge_type>2</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>36</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_90">
				<id>166</id>
				<edge_type>2</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>15</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_91">
				<id>167</id>
				<edge_type>2</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>39</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_92">
				<id>168</id>
				<edge_type>2</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>37</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_93">
				<id>169</id>
				<edge_type>2</edge_type>
				<source_obj>37</source_obj>
				<sink_obj>15</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_94">
				<id>170</id>
				<edge_type>4</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>11</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_95">
				<id>171</id>
				<edge_type>4</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>35</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_96">
				<id>172</id>
				<edge_type>4</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>35</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_97">
			<mId>1</mId>
			<mTag>bgr2gray&lt;16, 0, 1080, 1920, 1, 2, 2&gt;_Pipeline_columnloop</mTag>
			<mNormTag>bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>2</item>
				<item>3</item>
				<item>4</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>1926</mMinLatency>
			<mMaxLatency>1926</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_98">
			<mId>2</mId>
			<mTag>Entry</mTag>
			<mNormTag>Entry</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>10</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_99">
			<mId>3</mId>
			<mTag>columnloop</mTag>
			<mNormTag>columnloop</mNormTag>
			<mType>1</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>15</item>
				<item>37</item>
			</basic_blocks>
			<mII>1</mII>
			<mDepth>6</mDepth>
			<mMinTripCount>1920</mMinTripCount>
			<mMaxTripCount>1920</mMaxTripCount>
			<mMinLatency>1924</mMinLatency>
			<mMaxLatency>1924</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_100">
			<mId>4</mId>
			<mTag>Return</mTag>
			<mNormTag>Return</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>39</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="26" tracking_level="0" version="0">
		<count>27</count>
		<item_version>0</item_version>
		<item class_id="27" tracking_level="0" version="0">
			<first>4</first>
			<second class_id="28" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>7</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>8</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>9</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>11</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>12</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>13</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>14</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>19</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>20</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>21</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>22</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>23</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>24</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>25</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>26</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>27</first>
			<second>
				<first>2</first>
				<second>2</second>
			</second>
		</item>
		<item>
			<first>28</first>
			<second>
				<first>1</first>
				<second>2</second>
			</second>
		</item>
		<item>
			<first>29</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>30</first>
			<second>
				<first>3</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>31</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>32</first>
			<second>
				<first>4</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>33</first>
			<second>
				<first>5</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>34</first>
			<second>
				<first>5</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>35</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>36</first>
			<second>
				<first>5</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>38</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="29" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="30" tracking_level="0" version="0">
			<first>10</first>
			<second class_id="31" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>15</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>37</first>
			<second>
				<first>1</first>
				<second>6</second>
			</second>
		</item>
		<item>
			<first>39</first>
			<second>
				<first>2</first>
				<second>2</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="32" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="33" tracking_level="1" version="0" object_id="_101">
			<region_name>columnloop</region_name>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>15</item>
				<item>37</item>
			</basic_blocks>
			<nodes>
				<count>0</count>
				<item_version>0</item_version>
			</nodes>
			<anchor_node>-1</anchor_node>
			<region_type>8</region_type>
			<interval>1</interval>
			<pipe_depth>6</pipe_depth>
			<mDBIIViolationVec class_id="34" tracking_level="0" version="0">
				<count>0</count>
				<item_version>0</item_version>
			</mDBIIViolationVec>
		</item>
	</regions>
	<dp_fu_nodes class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="37" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="38" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core>
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

