# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_2/design_1_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_2 || ORIG_REF_NAME==design_1_processing_system7_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_threshold_accel_0_2/design_1_threshold_accel_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_threshold_accel_0_2 || ORIG_REF_NAME==design_1_threshold_accel_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_5 || ORIG_REF_NAME==design_1_xbar_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_2/design_1_axi_mem_intercon_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_2 || ORIG_REF_NAME==design_1_axi_mem_intercon_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_2/design_1_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_2 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_4/design_1_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_4 || ORIG_REF_NAME==design_1_xbar_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_2/design_1_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_2 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# XDC: w:/vivado/threshold-1/threshold-1.gen/sources_1/bd/design_1/design_1_ooc.xdc
