// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cvtcolor_og_bgr2gray_16_0_1080_1920_1_2_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_dout,
        p_src_rows_num_data_valid,
        p_src_rows_fifo_cap,
        p_src_rows_empty_n,
        p_src_rows_read,
        p_src_cols_dout,
        p_src_cols_num_data_valid,
        p_src_cols_fifo_cap,
        p_src_cols_empty_n,
        p_src_cols_read,
        imgInput0_data_dout,
        imgInput0_data_num_data_valid,
        imgInput0_data_fifo_cap,
        imgInput0_data_empty_n,
        imgInput0_data_read,
        imgOutput0_data_din,
        imgOutput0_data_num_data_valid,
        imgOutput0_data_fifo_cap,
        imgOutput0_data_full_n,
        imgOutput0_data_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_dout;
input  [2:0] p_src_rows_num_data_valid;
input  [2:0] p_src_rows_fifo_cap;
input   p_src_rows_empty_n;
output   p_src_rows_read;
input  [31:0] p_src_cols_dout;
input  [2:0] p_src_cols_num_data_valid;
input  [2:0] p_src_cols_fifo_cap;
input   p_src_cols_empty_n;
output   p_src_cols_read;
input  [23:0] imgInput0_data_dout;
input  [2:0] imgInput0_data_num_data_valid;
input  [2:0] imgInput0_data_fifo_cap;
input   imgInput0_data_empty_n;
output   imgInput0_data_read;
output  [7:0] imgOutput0_data_din;
input  [2:0] imgOutput0_data_num_data_valid;
input  [2:0] imgOutput0_data_fifo_cap;
input   imgOutput0_data_full_n;
output   imgOutput0_data_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_rows_read;
reg p_src_cols_read;
reg imgInput0_data_read;
reg imgOutput0_data_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_rows_blk_n;
reg    p_src_cols_blk_n;
wire   [15:0] empty_fu_73_p1;
reg   [15:0] empty_reg_112;
reg    ap_block_state1;
wire   [15:0] empty_46_fu_77_p1;
reg   [15:0] empty_46_reg_117;
wire    grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start;
wire    grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_done;
wire    grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_idle;
wire    grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_ready;
wire    grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgInput0_data_read;
wire   [7:0] grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgOutput0_data_din;
wire    grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgOutput0_data_write;
reg    grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln5576_fu_89_p2;
wire    ap_CS_fsm_state3;
reg   [15:0] i_fu_48;
wire   [15:0] add_ln5576_fu_94_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg = 1'b0;
#0 i_fu_48 = 16'd0;
end

cvtcolor_og_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start),
    .ap_done(grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_done),
    .ap_idle(grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_idle),
    .ap_ready(grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_ready),
    .imgInput0_data_dout(imgInput0_data_dout),
    .imgInput0_data_num_data_valid(3'd0),
    .imgInput0_data_fifo_cap(3'd0),
    .imgInput0_data_empty_n(imgInput0_data_empty_n),
    .imgInput0_data_read(grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgInput0_data_read),
    .imgOutput0_data_din(grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgOutput0_data_din),
    .imgOutput0_data_num_data_valid(3'd0),
    .imgOutput0_data_fifo_cap(3'd0),
    .imgOutput0_data_full_n(imgOutput0_data_full_n),
    .imgOutput0_data_write(grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgOutput0_data_write),
    .empty(empty_reg_112)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln5576_fu_89_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln5576_fu_89_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_ready == 1'b1)) begin
            grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_48 <= 16'd0;
    end else if (((icmp_ln5576_fu_89_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_48 <= add_ln5576_fu_94_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_46_reg_117 <= empty_46_fu_77_p1;
        empty_reg_112 <= empty_fu_73_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5576_fu_89_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5576_fu_89_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgInput0_data_read = grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgInput0_data_read;
    end else begin
        imgInput0_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgOutput0_data_write = grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgOutput0_data_write;
    end else begin
        imgOutput0_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_blk_n = p_src_cols_empty_n;
    end else begin
        p_src_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_read = 1'b1;
    end else begin
        p_src_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_blk_n = p_src_rows_empty_n;
    end else begin
        p_src_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_read = 1'b1;
    end else begin
        p_src_rows_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln5576_fu_89_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln5576_fu_94_p2 = (i_fu_48 + 16'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_46_fu_77_p1 = p_src_rows_dout[15:0];

assign empty_fu_73_p1 = p_src_cols_dout[15:0];

assign grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start = grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg;

assign icmp_ln5576_fu_89_p2 = ((i_fu_48 == empty_46_reg_117) ? 1'b1 : 1'b0);

assign imgOutput0_data_din = grp_bgr2gray_16_0_1080_1920_1_2_2_Pipeline_columnloop_fu_64_imgOutput0_data_din;

endmodule //cvtcolor_og_bgr2gray_16_0_1080_1920_1_2_2_s
