// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module threshold_accel_Threshold_0_0_1080_1920_1_2_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_mat_rows_dout,
        p_src_mat_rows_num_data_valid,
        p_src_mat_rows_fifo_cap,
        p_src_mat_rows_empty_n,
        p_src_mat_rows_read,
        p_src_mat_cols_dout,
        p_src_mat_cols_num_data_valid,
        p_src_mat_cols_fifo_cap,
        p_src_mat_cols_empty_n,
        p_src_mat_cols_read,
        in_mat_data_dout,
        in_mat_data_num_data_valid,
        in_mat_data_fifo_cap,
        in_mat_data_empty_n,
        in_mat_data_read,
        out_mat_data_din,
        out_mat_data_num_data_valid,
        out_mat_data_fifo_cap,
        out_mat_data_full_n,
        out_mat_data_write,
        thresh_dout,
        thresh_num_data_valid,
        thresh_fifo_cap,
        thresh_empty_n,
        thresh_read,
        maxval_dout,
        maxval_num_data_valid,
        maxval_fifo_cap,
        maxval_empty_n,
        maxval_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_mat_rows_dout;
input  [2:0] p_src_mat_rows_num_data_valid;
input  [2:0] p_src_mat_rows_fifo_cap;
input   p_src_mat_rows_empty_n;
output   p_src_mat_rows_read;
input  [31:0] p_src_mat_cols_dout;
input  [2:0] p_src_mat_cols_num_data_valid;
input  [2:0] p_src_mat_cols_fifo_cap;
input   p_src_mat_cols_empty_n;
output   p_src_mat_cols_read;
input  [7:0] in_mat_data_dout;
input  [2:0] in_mat_data_num_data_valid;
input  [2:0] in_mat_data_fifo_cap;
input   in_mat_data_empty_n;
output   in_mat_data_read;
output  [7:0] out_mat_data_din;
input  [2:0] out_mat_data_num_data_valid;
input  [2:0] out_mat_data_fifo_cap;
input   out_mat_data_full_n;
output   out_mat_data_write;
input  [7:0] thresh_dout;
input  [2:0] thresh_num_data_valid;
input  [2:0] thresh_fifo_cap;
input   thresh_empty_n;
output   thresh_read;
input  [7:0] maxval_dout;
input  [2:0] maxval_num_data_valid;
input  [2:0] maxval_fifo_cap;
input   maxval_empty_n;
output   maxval_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_mat_rows_read;
reg p_src_mat_cols_read;
reg in_mat_data_read;
reg out_mat_data_write;
reg thresh_read;
reg maxval_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_mat_rows_blk_n;
reg    p_src_mat_cols_blk_n;
reg    thresh_blk_n;
reg    maxval_blk_n;
reg   [7:0] maxval_read_reg_132;
reg    ap_block_state1;
reg   [7:0] thresh_1_reg_137;
wire   [15:0] empty_fu_93_p1;
reg   [15:0] empty_reg_142;
wire   [15:0] empty_41_fu_97_p1;
reg   [15:0] empty_41_reg_147;
wire    grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start;
wire    grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_done;
wire    grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_idle;
wire    grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_ready;
wire    grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_in_mat_data_read;
wire   [7:0] grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_out_mat_data_din;
wire    grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_out_mat_data_write;
reg    grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln64_fu_109_p2;
wire    ap_CS_fsm_state3;
reg   [15:0] i_fu_54;
wire   [15:0] add_ln64_fu_114_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start_reg = 1'b0;
#0 i_fu_54 = 16'd0;
end

threshold_accel_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start),
    .ap_done(grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_done),
    .ap_idle(grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_idle),
    .ap_ready(grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_ready),
    .in_mat_data_dout(in_mat_data_dout),
    .in_mat_data_num_data_valid(3'd0),
    .in_mat_data_fifo_cap(3'd0),
    .in_mat_data_empty_n(in_mat_data_empty_n),
    .in_mat_data_read(grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_in_mat_data_read),
    .out_mat_data_din(grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_out_mat_data_din),
    .out_mat_data_num_data_valid(3'd0),
    .out_mat_data_fifo_cap(3'd0),
    .out_mat_data_full_n(out_mat_data_full_n),
    .out_mat_data_write(grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_out_mat_data_write),
    .empty(empty_reg_142),
    .thresh_1(thresh_1_reg_137),
    .maxval_load(maxval_read_reg_132)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln64_fu_109_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln64_fu_109_p2 == 1'd0))) begin
            grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_ready == 1'b1)) begin
            grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_54 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln64_fu_109_p2 == 1'd0))) begin
        i_fu_54 <= add_ln64_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_41_reg_147 <= empty_41_fu_97_p1;
        empty_reg_142 <= empty_fu_93_p1;
        maxval_read_reg_132 <= maxval_dout;
        thresh_1_reg_137 <= thresh_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln64_fu_109_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln64_fu_109_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_mat_data_read = grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_in_mat_data_read;
    end else begin
        in_mat_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        maxval_blk_n = maxval_empty_n;
    end else begin
        maxval_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        maxval_read = 1'b1;
    end else begin
        maxval_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_mat_data_write = grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_out_mat_data_write;
    end else begin
        out_mat_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_cols_blk_n = p_src_mat_cols_empty_n;
    end else begin
        p_src_mat_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_cols_read = 1'b1;
    end else begin
        p_src_mat_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_rows_blk_n = p_src_mat_rows_empty_n;
    end else begin
        p_src_mat_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_rows_read = 1'b1;
    end else begin
        p_src_mat_rows_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        thresh_blk_n = thresh_empty_n;
    end else begin
        thresh_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        thresh_read = 1'b1;
    end else begin
        thresh_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln64_fu_109_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln64_fu_114_p2 = (i_fu_54 + 16'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (maxval_empty_n == 1'b0) | (thresh_empty_n == 1'b0) | (p_src_mat_cols_empty_n == 1'b0) | (p_src_mat_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_41_fu_97_p1 = p_src_mat_rows_dout[15:0];

assign empty_fu_93_p1 = p_src_mat_cols_dout[15:0];

assign grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start = grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_ap_start_reg;

assign icmp_ln64_fu_109_p2 = ((i_fu_54 == empty_41_reg_147) ? 1'b1 : 1'b0);

assign out_mat_data_din = grp_Threshold_0_0_1080_1920_1_2_2_Pipeline_colLoop_fu_82_out_mat_data_din;

endmodule //threshold_accel_Threshold_0_0_1080_1920_1_2_2_s
